In [ ]:
# https://www.kaggle.com/datasets/megan3/groningen-crime-data-19962021

In [23]:
# import libraries
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [37]:
# load dataset
csvFile = pd.read_csv("aangifte-politie_totaal.csv")
df = pd.DataFrame(csvFile)
df.head()

,hoofdgroep,main_group,aangifte,subgroup,Year_1996,Year_1997,Year_1998,Year_1999,Year_2000,Year_2001,...,Year_2012,Year_2013,Year_2014,Year_2015,Year_2016,Year_2017,Year_2018,Year_2019,Year_2020,Year_2021
0,vermogensdelicten,property crimes,diefstal auto,theft car,327,428,351,334,262,330,...,67,75,70,63,82,50,43,31,27,17
1,vermogensdelicten,property crimes,diefstal motor/scooter,theft motorcycle/scooter,28,30,26,28,19,45,...,36,31,23,64,27,49,46,14,29,35
2,vermogensdelicten,property crimes,diefstal bromfiets/snorfiets,theft moped,438,404,418,560,301,271,...,485,485,454,488,397,332,377,401,317,259
3,vermogensdelicten,property crimes,diefstal fiets,theft bike,2842,319,3058,3322,3512,3098,...,3272,3605,3291,3549,3408,2363,1982,1983,1446,1809
4,vermogensdelicten,property crimes,diefstal af/uit auto,theft from car,2657,2712,2918,3087,3058,3251,...,905,931,885,1091,948,522,384,478,357,228

In [15]:
# data cleaning
np.where(pd.isnull(df))

(array([], dtype=int64), array([], dtype=int64))

In [18]:
df.describe()

,Year_1996,Year_1997,Year_1998,Year_1999,Year_2000,Year_2001,Year_2002,Year_2003,Year_2004,Year_2005,...,Year_2012,Year_2013,Year_2014,Year_2015,Year_2016,Year_2017,Year_2018,Year_2019,Year_2020,Year_2021
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,...,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,963.733333,1094.333333,1325.133333,1181.466667,1324.666667,1194.666667,1032.733333,1102.066667,1123.666667,949.400000,...,910.533333,962.733333,926.133333,900.866667,881.666667,704.266667,547.400000,527.333333,500.400000,468.466667
std,1121.827620,1127.693643,1197.079414,1203.999043,1228.328636,1210.687034,1060.815486,1134.153962,1098.580036,1048.789425,...,971.665865,1051.447266,987.146527,985.249052,960.588560,746.728146,621.011364,581.649584,501.113303,550.075951
min,28.000000,30.000000,26.000000,28.000000,19.000000,45.000000,22.000000,32.000000,51.000000,32.000000,...,36.000000,31.000000,23.000000,57.000000,27.000000,45.000000,27.000000,14.000000,27.000000,17.000000
25%,199.000000,231.500000,326.500000,293.000000,281.500000,235.500000,237.000000,256.000000,293.000000,141.500000,...,226.500000,221.000000,264.000000,229.000000,235.500000,163.000000,110.500000,110.500000,115.000000,80.000000
50%,327.000000,428.000000,926.000000,560.000000,975.000000,458.000000,457.000000,529.000000,944.000000,562.000000,...,513.000000,687.000000,499.000000,488.000000,556.000000,453.000000,377.000000,401.000000,357.000000,259.000000
75%,1554.000000,1871.000000,2607.500000,1862.500000,2264.000000,1862.500000,1736.000000,1656.000000,1677.500000,1205.500000,...,1077.000000,1108.000000,1121.500000,1015.000000,955.000000,895.500000,778.000000,656.500000,683.000000,558.000000
max,3162.000000,3229.000000,3058.000000,3322.000000,3512.000000,3251.000000,3276.000000,3513.000000,3544.000000,3239.000000,...,3272.000000,3605.000000,3291.000000,3549.000000,3408.000000,2363.000000,1982.000000,1983.000000,1446.000000,1809.000000

In [38]:
# normalize the dataset
df = df.drop(['main_group', 'subgroup'], axis=1)
s0 = df.iloc[:,2:]
df.iloc[:,2:] = (s0 - s0.mean()) / (s0.max() - s0.min())
df

,hoofdgroep,aangifte,Year_1996,Year_1997,Year_1998,Year_1999,Year_2000,Year_2001,Year_2002,Year_2003,...,Year_2012,Year_2013,Year_2014,Year_2015,Year_2016,Year_2017,Year_2018,Year_2019,Year_2020,Year_2021
0,vermogensdelicten,diefstal auto,-0.203170,-0.208294,-0.321284,-0.257276,-0.304228,-0.269703,-0.222721,-0.233285,...,-0.260672,-0.248386,-0.261975,-0.239939,-0.236518,-0.282255,-0.258005,-0.252074,-0.333615,-0.251935
1,vermogensdelicten,diefstal motor/scooter,-0.298575,-0.332708,-0.428474,-0.350172,-0.373795,-0.358598,-0.310613,-0.307402,...,-0.270251,-0.260698,-0.276357,-0.239653,-0.252785,-0.282686,-0.256471,-0.260708,-0.332206,-0.241890
2,vermogensdelicten,diefstal bromfiets/snorfiets,-0.167752,-0.215797,-0.299186,-0.188666,-0.293062,-0.288106,-0.208584,-0.227253,...,-0.131500,-0.133669,-0.144472,-0.118232,-0.143350,-0.160598,-0.087161,-0.064161,-0.129246,-0.116890
3,vermogensdelicten,diefstal fiets,0.599319,-0.242367,0.571526,0.649828,0.626205,0.593679,0.689387,0.556143,...,0.729749,0.739302,0.723643,0.758343,0.747215,0.715588,0.733811,0.739292,0.666385,0.748065
4,vermogensdelicten,diefstal af/uit auto,0.540289,0.505679,0.525352,0.578486,0.496231,0.641402,0.570150,0.376022,...,-0.001710,-0.008879,-0.012587,0.054448,0.019619,-0.078631,-0.083581,-0.025055,-0.101057,-0.134189
5,vermogensdelicten,diefstal af/uit bedrijf,-0.257413,0.145254,0.143755,0.090933,0.150969,0.192244,0.196148,0.056287,...,-0.174763,-0.171162,-0.148756,-0.152883,-0.145716,-0.200719,-0.162864,-0.144405,-0.224383,-0.177716
6,vermogensdelicten,diefstal uit woning,0.701425,0.566948,0.482146,-0.273366,0.273213,0.183198,0.269289,-0.259715,...,0.104594,0.090170,0.104610,0.008343,0.021394,-0.044981,0.106189,0.056712,-0.067230,-0.066109
7,vermogensdelicten,winkeldiefstal,0.041566,-0.035115,-0.045229,0.018073,-0.044565,-0.337388,0.056320,0.032730,...,-0.033539,-0.024827,0.014953,0.010920,0.021986,0.103422,0.150179,0.167936,0.206906,0.068936
8,vermogensdelicten,zakkenrollen,-0.213380,-0.281755,-0.309411,-0.244829,-0.269587,-0.229778,-0.225794,-0.198238,...,-0.124083,-0.077150,-0.146920,-0.119091,-0.096323,-0.168795,-0.164910,-0.137295,-0.261734,-0.214546
9,vermogensdelicten,beroving (wo. tasjesroof),-0.230611,-0.274252,-0.362181,-0.276402,-0.308236,-0.310252,-0.263286,-0.252820,...,-0.249856,-0.248107,-0.262281,-0.241657,-0.246870,-0.284412,-0.266189,-0.240901,-0.322340,-0.248586
10,vermogensdelicten,Overige vermogensdelicten,-0.298575,0.667292,0.546790,0.614612,0.490219,0.620503,-0.307232,0.692598,...,0.572765,0.550718,0.579825,0.459947,0.476289,0.538712,0.669361,0.558490,0.621987,0.524293
11,overige delicten,mishandeling/geweld,-0.058626,-0.070126,-0.131640,-0.087270,-0.100105,-0.082554,-0.016206,-0.045121,...,-0.005109,-0.016154,0.005467,0.000897,-0.004338,0.061576,0.129719,0.074488,0.050458,0.030990
12,overige delicten,zedenmisdrijf,-0.263795,-0.299885,-0.398461,-0.330439,-0.339154,-0.339884,-0.286027,-0.287293,...,-0.248002,-0.243910,-0.256467,-0.231921,-0.238884,-0.266293,-0.230384,-0.222617,-0.281466,-0.219010
13,overige delicten,bedreiging/mensenhandel,-0.225824,-0.265187,-0.337445,-0.266080,-0.268728,-0.239135,-0.176931,-0.164627,...,-0.122847,-0.127793,-0.130702,-0.124246,-0.121463,-0.108398,-0.063120,-0.048925,-0.051022,-0.061644
14,Vernieling cq zaakbeschadiging,Vernieling cq. zaakbeschadiging,0.335120,0.340315,0.363742,0.322566,0.264624,0.224371,0.236099,0.261975,...,0.215225,0.180545,0.212016,0.174723,0.199744,0.458470,-0.216573,-0.200779,0.558562,0.360231